### ISSUE TITLE
Update Docker instructions

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/training-specific-template#102]
The docker image instructions that we have at `docker-install/INSTALLATION-INSTRUCTIONS.md` are quite out of date. 

We should update them to remove references to kitematic and show how to set arguments directly in the new Docker Desktop app

We can also add some updates to the `virtual-workshop/using-docker-post-workshop.md` that show off some of the ways that settings (ports, password, volumes) can be made in the Docker Desktop app, which might be easier for some users than the pure command-line options currently shown.

**Comment by sjspielman** [comment]
Closing this in favor of #107
