### ISSUE TITLE
Ensure upload size limit is correct

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/training-specific-template#103]
We _may_ need to update the instructions about direct file upload - limit may no longer 1GB, but probably 50 MB. 
https://github.com/AlexsLemonade/training-specific-template/blob/615e672511c8abf0e2ef92d62f98649851c5e2dd/working-with-your-data/working-with-your-own-data.md

**Comment by sjspielman** [comment]
@jashapiro (or maybe @davidsmejia?) - can you confirm if we are still at 50 MB here as direct file size upload limit?

**Comment by sjspielman** [comment]
Giving this a bump @jashapiro @davidsmejia, thanks!

**Comment by jashapiro** [comment]
Looking at `/etc/nginx/sites-available/rstudio-server`  it seems like it is currently 100MB, but we could probably make it whatever we wanted. I also wouldn't quote 100MB as an exact limit, as that is probably only approximate given all the stuff that happens within the protocol.

**Comment by sjspielman** [comment]
Thanks, @jashapiro! I think give or take 100 MB is pretty reasonable as a "small" file size.

**Comment by sjspielman** [comment]
Closed by #146
