### ISSUE TITLE
Add new config variables

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/training-specific-template#106]
We should add (and then use!) some variables into `_config.yml`:

- Whether the workshop is remote or in-person
  - This comes into play for how `HOME.md` should look, and whether to use `participant-information.md` or `workshop-structure.md`
- Workshop name, one of `intro-r`, `intro-single-cell`, or `advanced-single-cell`
  - This will control the list of module links which are printed in `workshop-materials.md`
- Variable indicating how much space is available on the server (50 GB)
  - Should be used in `working-with-your-own-data.md` & `resources-for-consultation-sessions.md`
- Variable indicating limit on file upload size to server (50 MB; see also #103)
  - Should be used in `working-with-your-own-data.md` & `resources-for-consultation-sessions.md`
- Variable indicating how much time they will have access to server (6 months)
  - Should be used in `working-with-your-own-data.md` & new file for post-workshop instructions

**Comment by jashapiro** [comment]
The last three of these seem like they may be a bit of over-optimization. We are not likely to change the allocated sizes or timeframes on any regular basis, and while those values may be used in two places, it seems like the indirection cost may be higher than just updating as needed. 2 of 3 need no changes now, with the last (upload size limit) really being a server config issue.

**Comment by sjspielman** [comment]
The main reason I wanted to include them is _if_ they change, we don't have to go hunting through markdown files to update. So, if you have a strategy of remembering precisely every location where we mention those limits (perma-issue?) then sure, but I worry about catching it all in the future.

**Comment by jashapiro** [comment]
Yes, but that logic applies to just about any change we might make in the future. My point is that we have no plans to make those changes, so optimizing for it seems not worth the effort. There are probably a lot of places where we could turn paths and links and such into variables, but knowing which of those we actually will need is very hard to predict, and the indirection has costs of its own, including documentation.

**Comment by sjspielman** [comment]
We might also consider, from https://github.com/AlexsLemonade/training-specific-template/pull/131#discussion_r1306031441:

> Hmmm... maybe we want to make this a list in config and fill these names in automatically? Do we name ourselves elsewhere that we would reuse this?

Where "this" refers to the list of instructor names. See this commit for reference (`git` is trying to format this link and it's a little amusing): https://github.com/AlexsLemonade/training-specific-template/pull/131/commits/a99b7d1438f1a3c9bbbc7ebde8856652d1e9f944#diff-0f520386044fbb18b240e0ca96aba236a8e0a71cc8b068407af25342cff295fc

**Comment by sjspielman** [comment]
Clpsed by #133
