### ISSUE TITLE
Add GHA to copy completed notebooks

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/training-specific-template#111]
I'm opening this issue to supplant #65 

> There seems to be a bug in https://htmlpreview.github.io/ that is preventing proper rendering of the TOC in our notebook files. There may be fix soon, but who knows...
>
> We could remove reliance on htmlpreview by copying html files from the training-modules repo into this one (or the cloned repo). I haven't thought about the best way to do this yet, (it probably involves a GHA and a script) but it might be something to pursue for the next round.

For this, we probably want something similar (in that files are being copied...not much else is similar to be fair...) to what we do for exercise notebooks: https://github.com/AlexsLemonade/exercise-notebook-answers/blob/b54241f598bf81ebf5632f7a1127c6f33fc9e20f/.github/workflows/exercises-to-training.yml

One question I still haven't thought all the way through yet is whether to include this GHA in _this_ repo, or over in [AlexsLemonade/training-modules](https://github.com/AlexsLemonade/training-modules), so we may end up moving this issue over to that repo.

Either way, it will be manually triggered and take two input variables:
- the name of the tag in `training-modules` that contains the notebook versions to copy
- the name of the workshop, which will dictate _which_ notebooks to copy...
  - `intro-R` - notebooks in `intro-to-R-tidyverse`
  - `intro-single-cell` - notebooks in _both_  `intro-to-R-tidyverse` and `scRNA-seq`
  - `advanced-single-cell` - notebooks in `scRNA-seq-advanced`
  - ....Alternatively, it seems fine to just copy all notebooks and skip this input variable; the notebooks won't hurt anyone to be here!

**Comment by sjspielman** [comment]
This seems like a possibility too (but I do worry [should I?] about longterm maintenance of actions like this?) -  https://github.com/marketplace/actions/copy-files-to-another-repository

**Comment by jashapiro** [comment]
> This seems like a possibility too (but I do worry [should I?] about longterm maintenance of actions like this?) - https://github.com/marketplace/actions/copy-files-to-another-repository

Since that action hasn't been updated in over a year, I _would_ be worried about maintenance. Copying files as we do between notebook answers and training is not particularly onerous, and could almost certainly be done more simply than we do there. It could probably be done without any of the token manipulation we have in `exercise-notebook-answers` as long as we make the PR in this repo and download the files from a public repo (which `exercise-notebook-answers` is not).

**Comment by sjspielman** [comment]
Closed by #132
