### ISSUE TITLE
Add file to handle participant information and workshop structure

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/training-specific-template#115]
Depending if a workshop is remote or in-person, we have had one of these files in the navbar:

- `participant-information.md` (see [here](https://github.com/AlexsLemonade/2023-june-training/blob/4ccd2df912fa636db1e7c2156df650132be8d900/workshop/participant_information.md) for most recent version)
- [`workshop-structure.md`](https://github.com/AlexsLemonade/training-specific-template/blob/615e672511c8abf0e2ef92d62f98649851c5e2dd/virtual-workshop/workshop-structure.md)

Rather than having to modify the `_config.yml`'s header pages section to achieve this, let's create 1 markdown file that will live in the `workshop` directory whose full title will be `Workshop Information`, and navbar title `Information`. The body of this file will just be an `if` statement using the first new config variable created in #106 (is a workshop remote or in-person), and then one of those files would be `%include%`'ed based on that value.

**Comment by jashapiro** [comment]
> I am back to note that I had forgotten the key detail that `%include%`'d files _must live in `_includes/`_. The precise scope of this issue may need to be rethought; will circle back!!

You can use `% include_relative path/to/file.html %` to be more flexible.
See https://jekyllrb.com/docs/includes/

**Comment by sjspielman** [comment]
🌮 @jashapiro, who has excellent literacy skills reading jekyll docs (see what I did there).

**Comment by sjspielman** [comment]
This is all set with changes in #133.
