### ISSUE TITLE
Revisit zoom procedures

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/training-specific-template#151]
I posted this comment in #149, but we all forgot about it during review!

> I started to do `zoom-procedures.md` alt texts, but I stopped pretty soon in since I wonder if we actually want to purge a lot of this content. Zoom screenshots are pretty out of date (but probably not too problematic?), but mostly I feel like people know what they're doing in 2023 (well, 2024 by the next workshop!) vs 2020. What do you think? Go back and add the alt text, or dramatically reduce the page (can be separate PR).

Here is May 2023 Zoom procedures page, which matches the current version here in `template-refresh` (except installation instructions have been moved out into the new `software-installation.md`).
https://alexslemonade.github.io/2023-may-training/virtual-setup/zoom-procedures.html

I'm thinking we can get rid of the "how to use Zoom" aspects (incl screenshots) that are _not_ specific to our workshop procedures. We can link something like this for general Zoom information: https://support.zoom.us/hc/en-us/articles/360034967471-Getting-started-guide-for-new-users. Basically, this is all of "General tips for using Zoom during workshops."

We should instead focus mostly (only?) on our Zoom practices (procedures, if you will!) during workshop rather than "here's the button to click" kind of things.
  - Reminder for where to find installation/screen share instructions
  - Small sections explaining how we use Zoom in workshops:
    - instruction in Zoom, consultation in Slack with option to Zoom 1:1
    - who to message for help (not the instructor!)
    - getting help in breakout rooms breakout 
    - we are recording

Tagging @jashapiro for discussion!

**Comment by sjspielman** [comment]
@jashapiro giving this lil bump for any thoughts!

**Comment by jashapiro** [comment]
Trimming these is fine. I don't think it matters much one way or the other. I also don't think the alt links are a priority, so if this gets just left as is for now, that is also fine.

**Comment by sjspielman** [comment]
Closed by #152
