### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/training-specific-template#155]
`template-refresh` has been released!

We should tag a new release as `2023.10`, but only after finalizing the external instructions which still has placeholder text.

**Comment by sjspielman** [comment]
Came over to do this, but then had a thought that maybe we'd benefit from one quick additional change - would it be help to add a section to README `contents of this repository` with a quick explanation of what's in each folder?

@Jen-OMalley since you tested out the instructions last week, do you think having this information might have helped you get your bearings, or would it have been excessive/distracting information?

**Comment by Jen-OMalley** [comment]
I think the folders and files are named clearly enough that I'd be able to explore and find what I was looking for without much more guidance! If you do decide to add that, you can definitely keep it very brief.

**Comment by sjspielman** [comment]
I'm thinking about just adding one sentence to the README, "Please see `CONTENTS.md` for more detailed information about the contents of this repository." In `CONTENTS.md`, I'd make a _really brief_ bulleted list of what each folder/file generally is. This way folks can refer to it if they want without it being in the way. The more I think about it too, I think this might also help us in the future if we ever want to move things around again.

**Comment by sjspielman** [comment]
🎉 https://github.com/AlexsLemonade/training-specific-template/releases/tag/2023.10
