### ISSUE TITLE
working-with-your-data: ssh + cp = scp

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/training-specific-template#31]
This idea is from a discussion I've had on Slack with @kurtwheeler . But basically participants can practice the mechanics of `scp` by understanding how `cp` works. So I may add an initial exercise/link in the `working-with-your-data/working-with-your-own-data.md#upload-data-that-is-on-a-ssh-server` that has them practice with `cp`, then login to their ssh server, the lastly put together that `scp` is  basically `cp` but with a password.

**Comment by jaclyn-taroni** [comment]
If you’d like this to be included as part of 2020 June, can you make a duplicate issue on `2020-june-training` please?
