### ISSUE TITLE
working-with-your-data: Add a section about strategies for finding complicated file paths

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/training-specific-template#5]
Background: https://github.com/AlexsLemonade/training-admin/issues/253
This should be added to the working-with-your-data.md document and should include examples for windows and macs. 
Also should include how to get find the file path for your data if you use FileZilla since this seems to be a strategy employed by sequencing companies like Novogene (a situation of one of our participants) or encouraged by institutions that have ssh servers.

**Comment by sjspielman** [comment]
Closing since we no longer need this feature.
