### ISSUE TITLE
Host notebook html files in repo

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/training-specific-template#65]
There seems to be a bug in https://htmlpreview.github.io/ that is preventing proper rendering of the TOC in our notebook files. There may be fix soon, but who knows...

We could remove reliance on htmlpreview by copying html files from the training-modules repo into this one (or the cloned repo). I haven't thought about the best way to do this yet, (it probably involves a GHA and a script) but it might be something to pursue for the next round.

**Comment by sjspielman** [comment]
Closing in favor of #111
