### ISSUE TITLE
Add an Alex's Lemonade logo to the home page

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/training-specific-template#69]
Of the GitHub pages site. That's it, that's the thought.

**Comment by jashapiro** [comment]
Can we wait for the new one?

**Comment by jaclyn-taroni** [comment]
Yes (that is what prompted me filing this).

**Comment by jaclyn-taroni** [comment]
I do believe this is done, but the Data Lab logo is out of date now.

**Comment by jashapiro** [comment]
I think I updated it for the last training, but that needs to be ported to here (and the current training)
________________________________
