### ISSUE TITLE
working-with-your-data: Samba client `smbget` template script

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/training-specific-template#7]
Make a template script that shows how to `smbget` data from a Samba client (probably including if there are passwords and usernames associated or other pertinent options). 

More info: https://github.com/AlexsLemonade/training-admin/issues/253#issue-614972737

https://www.samba.org/samba/docs/current/man-html/smbget.1.html

This template script should be linked in the `working-with-your-data.md` document with further information about how to use it there. 

It should be in the `working-with-your-data` folder in this template repo.

**Comment by sjspielman** [comment]
Closing since we no longer need this feature.
