### ISSUE TITLE
Generate automated issue to update `slack-procedures.md` each training

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/training-specific-template#76]
In `slack-procedures.md`, the names of the team members who folks should direct message via Slack are listed and may change from training to training.

Therefore, we should generate an automated issue reminding us to update [the top of the `How we use Slack during workshops` section of the `slack-procedures.md`](https://github.com/AlexsLemonade/training-specific-template/blob/main/virtual-setup/slack-procedures.md#how-we-use-slack-during-workshops), as well as [the `Using direct messages during training` subsection](https://github.com/AlexsLemonade/training-specific-template/blob/main/virtual-setup/slack-procedures.md#using-direct-messages-during-training), as needed each training.

**Comment by sjspielman** [comment]
We should probably do this in the refresh epic, since this content is kinda stale again!

**Comment by sjspielman** [comment]
I went ahead an added a config variable for this in #133. 

Therefore, this automated issue should be - "check that the instructor list in `_config.yml` is correct for this workshop"; no need to actually edit any content beyond this!

**Comment by sjspielman** [comment]
Closing in favor of #124 which encompasses this individual task.

**Comment by sjspielman** [comment]
Even better, #124 obviated the need to do this at all 🎉
