### ISSUE TITLE
Fix broken links in `virtual-workshop/HOME.md`

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/training-specific-template#79]
I initially filed https://github.com/AlexsLemonade/training-specific-template/pull/78 to fix broken links on virtual workshop home page. A fix of that nature is good enough for the 2021 September workshop. For a longer-term template fix, we might consider going back to Markdown and let Jekyll build links.

**Comment by jashapiro** [comment]
I believe this was closed by #84
