### ISSUE TITLE
[Discussion/Running list] working-with-your-data: Most common errors and roadblocks

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/training-specific-template#8]
Background: https://github.com/AlexsLemonade/training-admin/issues/253

This is a longer term idea. As we encounter common errors and roadblocks from helping people process their data, we can add a `common errors` section to the `working-with-your-data.md` document. I would picture this moderately analogous to the [00- R debugging resources guide](https://github.com/AlexsLemonade/training-modules/blob/master/intro-to-R-tidyverse/00b-debugging_resources.md) but for shell scripting.

**Comment by sjspielman** [comment]
Closing since we no longer need this feature.
