### ISSUE TITLE
Create renv instructions

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/training-specific-template#99]
While we have the ability for people to download our Docker image for reproducing locally, we might also want to provide a lighter-weight option for installing just the R packages that we are using (especially for workshops that do not use other command line tools). For that we might have a quick intro to `renv`, along with instructions for downloading and applying the [`renv.lock` file from `training-modules`](https://github.com/AlexsLemonade/training-modules/blob/master/renv.lock) to a new project.

**Comment by sjspielman** [comment]
These instructions should be included in a single updated markdown file to live in `additional-resources` whose scope is "continuing to use our environment after the workshop," that should describe setup for both `docker` and `renv`.

**Comment by sjspielman** [comment]
Closing this in favor of #107
